## USB port
port: /dev/ttyACM1

##### Calibration ####
### accelerometer
accel_x_min: -258.0
accel_x_max: 267.0
accel_y_min: -267.7
accel_y_max: 260.0
accel_z_min: -280.0
accel_z_max: 281.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [0, 0, 0]
magn_ellipsoid_transform: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.03
gyro_average_offset_y: -0.02
gyro_average_offset_z: -0.01
